#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

"""
Takes a single image file as argument and open the series in the browser.

It assumes that your images are named C{something+1.ext}, C{something+2.ext}
where only the number changes and there is no other C{+number} in the file name.
"""

import glob
import optparse
import os
import re
import subprocess
import sys
import tempfile

def main():
    parser = optparse.OptionParser(usage="%prog imagefile+number.suffix", description="Opens up a sequence of pictures in a web browser.")

    (options, args) = parser.parse_args()
    del parser

    if len(args) == 0:
        print "Error: File argument needed."
        sys.exit(1)

    infile = args[0]
    if infile[0] != "/":
        infile = os.getcwd()+"/"+infile

    pattern = re.sub(r"\+\d+", "+*", infile)

    tempfile = write_html(sorted(glob.glob(pattern)))

    open_in_browser(tempfile)


def open_in_browser(filename):
    """
    Opens a file in a web browser.

    Currently, this is Firefox.

    @param filename: File to open.
    @type filename: str
    """
    subprocess.call(["firefox", filename])

def write_html(filelist):
    """
    Writes a HTML file with the given images.

    Some CSS is added to the header so that the pages look like in other PDF
    viewers. The target file is a temporary file.

    @param filelist: List with image files.
    @type filelist: list
    @return: HTML file name.
    @rtype: str
    """
    tmp = tempfile.NamedTemporaryFile(mode="w+", suffix=".html", delete=False)

    tmp.write(r"""<!doctype html>
              <html>
              <head>
              <style type="text/css">
              body {
                  background-color: #DDD;
                  padding: 10px;
              }
              img {
                  display: block;
                  margin: 0 auto 20px auto;
                  box-shadow: 4px 4px 10px #333;
              }
              </style>
              </head>
              <body>""")

    for arg in filelist:
        tmp.write('<img src="file://%s" width="100%%" />\n' % arg)

    tmp.write(r"""</body>
              </html>""")

    tmp.close()

    return tmp.name


if __name__ == "__main__":
	main()
